### PR TITLE
Add push notification permission callback closure.

### PR DESCRIPTION
**Pull request by akshardarji**
Kindly please review it and update in the next version so that everybody can take advantage of it.

### CODE REVIEW

**Comment by kas-kad** [comment]
Hello, your feature proposal is reasonable, although wasn't ever requested so far. We'll revert back to you as soon as the feature is implemented in a forthcoming release.

**Comment by kas-kad** [comment]
Hello again @akshardarji. Could you please elaborate what is the main purpose of having this callback closure in your case? The may be another way to achieve your goals already implemented on our side.

**Comment by kas-kad** [comment]
I'd also like to point out that for iOS 9 and earlier there is no way to have such callback at all since it is not supported by Cocoa SDK

**Comment by akshardarji** [comment]
> Hello again @akshardarji. Could you please elaborate what is the main purpose of having this callback closure in your case? What is the feature you want to implement? 
 - I have few dependent actions once user allow/don't allow of the authentication AlertController hence I have created this closure to made it.

> There may be another way to achieve your goals already implemented on our side.
 - I haven't found any callback methods and property while I was doing work with that. If it's already 
 there some similar things, you should have to tell me the way that time while I did requested PR for the same. After long time back with thing which will be needed for revert my code or rework of something 

> I'd also like to point out that for iOS 9 and earlier there is no way to have such callback at all since it is not supported by Cocoa SDK
-  Yes, you are right. However in that case we can't do anything. Don't be consider below iOS 9 case.

**Comment by kas-kad** [comment]
I've added new SDK event for Notification Center authorization request (https://github.com/infobip/mobile-messaging-sdk-ios/releases/tag/5.1.7). For more details see: https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Library-events, event name "MMNotificationCenterAuthRequestFinished"

**Pull request closed without merging**
